export {default as About} from "../container/About/About"
export {default as Work} from "../container/Work/Work"
export {default as Skills} from "../container/Skills/Skills"
export {default as Testimonials} from "../container/Testimonils/Testimonials"
export {default as Header} from "../container/Header/Header"
export {default as Footer} from "../container/Footer/Footer"